---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-gitops-example
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/devopsforzombies/gitops
 